In [12]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('../data/facebook_combined.txt', sep=' ', names=['first_node', 'last_node'])
df.head()

   first_node  last_node
0           0          1
1           0          2
2           0          3
3           0          4
4           0          5

In [9]:
df.shape

(88234, 2)

In [10]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
88229    False
88230    False
88231    False
88232    False
88233    False
Length: 88234, dtype: bool

In [11]:
df.drop_duplicates(inplace=True)
df.shape

(88234, 2)

In [20]:
data = {
  "first_node": [420, 380, 390],
  "last_node": [420, 40, 45]
}

df2 = pd.DataFrame(data)
df2.head()

   first_node  last_node
0         420        420
1         380         40
2         390         45

In [34]:
df3 = df2.apply(lambda x: df.drop(x) if x['first_node'] == x['last_node'] else x, axis=1)
df3

0           first_node  last_node
0               0...
1    first_node    380
last_node      40
Name: 1, d...
2    first_node    390
last_node      45
Name: 2, d...
dtype: object

In [35]:
df4 = df2[df2['first_node'] != df2['last_node']]
df4.head()

   first_node  last_node
1         380         40
2         390         45

In [36]:
df5 = df[df['first_node'] != df['last_node']]
df5

       first_node  last_node
0               0          1
1               0          2
2               0          3
3               0          4
4               0          5
...           ...        ...
88229        4026       4030
88230        4027       4031
88231        4027       4032
88232        4027       4038
88233        4031       4038

[88234 rows x 2 columns]